import = ["~/.config/alacritty/themes/themes/gruvbox_dark.yaml"]

[font]
size = 13.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"
